name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    uses: libreadline

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
